teleop_twist_joy_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0

    axis_angular:  # Right thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 1.2
    scale_angular_turbo:
      yaw: 1.75

    require_enable_button: true
    enable_button: 6  # Left shoulder button
    enable_turbo_button: 7  # Right shoulder button
